### ISSUE TITLE
一个简单的说明

### ISSUE THREAD

**Issue by livoras** [livoras/blog#18]
本博客可能会很少活跃了（其实也一直没怎么活跃，惭愧），本人的 github、知乎等各大基佬社交平台帐号也应该不会再活跃了。谢谢大家一直以来对本博客的支持和关注（其实我就写过那么几篇文章，是在受宠若惊[捂头]）。

我还会在 Web 前端领域继续和大家一起学习、进步，也还会继续写东西——但是会以一种新的方式。如果有缘我们会再见。

再见了朋友们。:)

**Comment by livoras** [comment]
放closed里面吧

**Comment by liuqipeng417** [comment]
虚拟 dom 的文章非常赞，太可惜了
