### ISSUE TITLE
我使用listDiff算法比较出来的结果有点出入@Y-WinDow 如果没有key的情况下，无法判断，所以如果两个节点tagName不一样会整棵子树替换掉；如果有key的话，关键点就是怎么用list-diff使得对比的时候两个节点是同一个节点了

### ISSUE THREAD

**Issue by tongyafang** [livoras/blog#21]
@Y-WinDow 如果没有key的情况下，无法判断，所以如果两个节点tagName不一样会整棵子树替换掉；如果有key的话，关键点就是怎么用list-diff使得对比的时候两个节点是同一个节点了

_Originally posted by @livoras in https://github.com/livoras/blog/issues/13#issuecomment-161858437_

**Comment by livoras** [comment]
请到对应的仓库进行提问，这个是博客 issue。抱歉 close
